from pydantic_settings import BaseSettings, SettingsConfigDict
from functools import lru_cache


class Settings(BaseSettings):
    # Google Gemini key — user-provided at container deploy time
    GOOGLE_API_KEY: str

    # Per-container shared secret (generated by the server, injected as env var)
    CONTAINER_API_KEY: str

    # LLM model to use
    MODEL_NAME: str = "gemini-2.5-flash"

    # Max ReAct iterations before the agent gives up
    MAX_ITERATIONS: int = 10

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
