"""
Licenta Container — per-user AI agent service.

Entrypoint: uvicorn main:app --host 0.0.0.0 --port 8001

Authentication: every request must include the header
  X-API-Key: <CONTAINER_API_KEY>
The key is generated by the server when deploying this container and
injected as an environment variable.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import logging
from fastapi import FastAPI, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from config import settings
from API.agent_routes import router as agent_router

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Licenta Container Agent",
    description=(
        "Per-user AI agent container. "
        "All endpoints require X-API-Key header matching CONTAINER_API_KEY."
    ),
    version="1.0.0",
)

# ── API-key middleware ─────────────────────────────────────────────────────────

@app.middleware("http")
async def verify_api_key(request: Request, call_next):
    # Always allow health check without auth
    if request.url.path in ("/health", "/api/health", "/docs", "/openapi.json", "/redoc", "/api/agent/test"):
        return await call_next(request)

    api_key = request.headers.get("X-API-Key", "")
    if api_key != settings.CONTAINER_API_KEY:
        return JSONResponse(
            status_code=status.HTTP_401_UNAUTHORIZED,
            content={"detail": "Invalid or missing X-API-Key header"},
        )
    return await call_next(request)


# ── CORS ──────────────────────────────────────────────────────────────────────

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Routers ───────────────────────────────────────────────────────────────────

app.include_router(agent_router)


# ── Health ────────────────────────────────────────────────────────────────────

@app.get("/health", tags=["health"])
@app.get("/api/health", tags=["health"])
def health():
    return {"status": "ok", "model": settings.MODEL_NAME}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8001, reload=True)
