"""
Agent proxy routes for the APP Flask backend.

Stores the user's agent connection config in data/agent_config.json.
Proxies chat messages to the container using the container API key:

  server_proxy  →  POST {server_url}/api/containers/proxy-key/api/agent/...
                   X-API-Key: {api_key}

  direct        →  POST {container_url}/api/agent/...
                   X-API-Key: {api_key}

The API key is the per-container service key generated by the server
when the container is deployed.  No user JWT is involved.
The session is created lazily on the first chat call and reused.
"""
from __future__ import annotations

import json
import logging
import os
from pathlib import Path

import requests
from flask import Blueprint, jsonify, request

logger = logging.getLogger(__name__)

agent_bp = Blueprint("agent", __name__)

_CONFIG_PATH = Path(__file__).parent.parent.parent / "data" / "agent_config.json"

# ── Config persistence ────────────────────────────────────────────────────────

_DEFAULT_CONFIG: dict = {
    "mode": "server_proxy",       # "server_proxy" | "direct"
    "server_url": "http://localhost:8000",
    "api_key": "",               # container API key — works for both modes
    "container_url": "",         # only used in direct mode
    "session_id": None,
}


def _load_config() -> dict:
    if _CONFIG_PATH.exists():
        try:
            with open(_CONFIG_PATH) as f:
                data = json.load(f)
            # Migrate legacy fields from older config schema
            if "api_key" not in data:
                data["api_key"] = data.pop("container_api_key", "") or ""
            data.pop("jwt_token", None)  # no longer used
            # Back-fill any missing keys from defaults
            return {**_DEFAULT_CONFIG, **data}
        except Exception:
            pass
    return dict(_DEFAULT_CONFIG)


def _save_config(cfg: dict) -> None:
    _CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(_CONFIG_PATH, "w") as f:
        json.dump(cfg, f, indent=2)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _agent_headers(cfg: dict) -> dict:
    return {"X-API-Key": cfg["api_key"], "Content-Type": "application/json"}


def _agent_url(cfg: dict, path: str) -> str:
    """Build full URL for an agent endpoint given the current mode."""
    if cfg["mode"] == "server_proxy":
        base = cfg["server_url"].rstrip("/")
        # Uses the service-level proxy that validates by API key (no JWT)
        return f"{base}/api/containers/proxy-key/api/agent/{path.lstrip('/')}"
    else:
        base = cfg["container_url"].rstrip("/")
        return f"{base}/api/agent/{path.lstrip('/')}"


def _ensure_session(cfg: dict) -> tuple[dict, str | None]:
    """
    Create a new agent session if we don't have one (or it's stale).
    Returns the (possibly updated) config and an error string or None.
    """
    if cfg.get("session_id"):
        return cfg, None

    url = _agent_url(cfg, "init")
    try:
        resp = requests.post(
            url,
            headers=_agent_headers(cfg),
            json={"tools": []},   # no callback tools needed for simple prompts
            timeout=15,
        )
        resp.raise_for_status()
        session_id: str = resp.json()["session_id"]
        cfg["session_id"] = session_id
        _save_config(cfg)
        logger.info("Created agent session %s", session_id)
        return cfg, None
    except requests.RequestException as exc:
        logger.error("Failed to create agent session: %s", exc)
        return cfg, f"Could not connect to agent: {exc}"


# ── Routes ────────────────────────────────────────────────────────────────────

@agent_bp.get("/config")
def get_config():
    cfg = _load_config()
    safe = dict(cfg)
    safe["api_key_set"] = bool(safe.get("api_key"))
    return jsonify(safe)


@agent_bp.post("/config")
def save_config():
    data = request.get_json(force=True) or {}
    cfg = _load_config()

    cfg["mode"] = data.get("mode", cfg["mode"])
    cfg["server_url"] = data.get("server_url", cfg["server_url"])
    cfg["container_url"] = data.get("container_url", cfg["container_url"])

    # Only overwrite the API key if a non-empty one was sent
    if data.get("api_key"):
        cfg["api_key"] = data["api_key"]

    # Changing connection settings → invalidate existing session
    cfg["session_id"] = None

    _save_config(cfg)
    return jsonify({"ok": True})


@agent_bp.post("/chat")
def chat():
    data = request.get_json(force=True) or {}
    message: str = data.get("message", "")
    if not message:
        return jsonify({"error": "message is required"}), 400

    cfg = _load_config()

    # Validate config
    if not cfg.get("api_key"):
        return jsonify({"error": "API key not configured. Go to Settings → Agent Connection."}), 400
    if cfg["mode"] == "server_proxy" and not cfg.get("server_url"):
        return jsonify({"error": "Server URL not configured. Go to Settings → Agent Connection."}), 400
    if cfg["mode"] == "direct" and not cfg.get("container_url"):
        return jsonify({"error": "Container URL not configured. Go to Settings → Agent Connection."}), 400

    # Ensure we have a session
    cfg, err = _ensure_session(cfg)
    if err:
        return jsonify({"error": err}), 502

    url = _agent_url(cfg, "chat")
    try:
        resp = requests.post(
            url,
            headers=_agent_headers(cfg),
            json={"session_id": cfg["session_id"], "message": message},
            timeout=60,
        )
        if resp.status_code == 404:
            # Session expired — clear it and retry once
            cfg["session_id"] = None
            cfg, err = _ensure_session(cfg)
            if err:
                return jsonify({"error": err}), 502
            resp = requests.post(
                url,
                headers=_agent_headers(cfg),
                json={"session_id": cfg["session_id"], "message": message},
                timeout=60,
            )
        resp.raise_for_status()
        return jsonify(resp.json())
    except requests.RequestException as exc:
        logger.error("Agent chat failed: %s", exc)
        return jsonify({"error": f"Agent request failed: {exc}"}), 502
